Improve error handling while rebuilding packages

diff --git a/home/bin/executable_aur_rebuild b/home/bin/executable_aur_rebuild
--- a/home/bin/executable_aur_rebuild
+++ b/home/bin/executable_aur_rebuild
@@ -5,19 +5,23 @@ set -eu -o pipefail
 
 readonly PKG=$1
 
-if pacman -Qe "$PKG" > /dev/null ; then
+if ! pacman -Q "$PKG" &> /dev/null ; then
+    echo "$PKG is not installed, aborting"
+    exit 1
+fi
+
+if pacman -Qe "$PKG" &> /dev/null ; then
     EXP_OR_DEP="--asexplicit"
-elif pacman -Qd "$PKG" > /dev/null ; then
+elif pacman -Qd "$PKG" &> /dev/null ; then
     EXP_OR_DEP="--asdeps"
 else
-    echo "Could not determine if '$PKG' was explicitly installed"
-    exit 1
+    echo "Could not determine if '$PKG' was installed explicitly or as a dependency. Aborting."
+    exit 2
 fi
 readonly EXP_OR_DEP
 
 readonly REPO="aurto"
-REPOPATH=$(find /var/cache/pacman/ -maxdepth 1 -name "$REPO")
-readonly REPOPATH
+readonly REPOPATH=/var/cache/pacman/"$REPO"
 
 setup_build_dir() {
     local -r BUILD_ROOT="$HOME"/.cache/aurutils/sync
@@ -53,7 +57,7 @@ if [ $retval -eq 0 ] ; then
     # shellcheck disable=SC2046
     if [ $(echo "$PKGPATH" | wc -l) -ne 1 ] ; then
         echo "Unexpected number of packages matching $PKG in: $PKGPATH"
-        exit 2
+        exit 3
     fi
 
     # Install packages from database
